manifest:
  remotes:
    - name: github
      url-base: https://github.com

  projects:
    - name: zephyr
      remote: github
      repo-path: zephyrproject-rtos/zephyr
      import: 
        name-whitelist:
          - cmsis
      west-commands: scripts/west-commands.yml
  self:
    path: application
